language: java
sudo: required
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "5033" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/lab234.jar -t 5033/se234-lab10-backend
  .
- docker push 5033/se234-lab10-backend
- docker pull 5033/se234-lab10-client
script:
- docker-compose -H "$DOCKER_HOST" up -d
cashe:
  directories:
  - "$HOME/.m2"
env:
  global:
    secure: q3FioVMQ7Ni9Exgs7/dDDwed1S8i4kH7jUa1VDSGzbBrjBDcGzb1wGjRHkzX+uNZOFnVijQpI8x/PvbnOyEfrN+pMMkaXFA+qvIE0ngNdYB2YS4k4pdLIXv8PHMMlYBhwwUzXUrdpxfSRc4j2TBcEYEmE1q9Awg9xorE1T9baLv1KYOvuQsHOZR+w2mp9gT8xxDj8IGt0hMDWO/pgUyBsx2G8l2YnPiaoT+fOkNJCAfnxLbHq2gOdzqIZQYERmyhfuttRGi1bq5kx9qVVfBJHcfj0cchxVAG4hFAGhNgWdwRFbHHIDEYpl/JA0DX2A/wz7iaCbrLEK9hx/clK7SjClbzkVc1Z+hTOuLg4/IgMnX//qnkcfttCbXnjUlOrfJH78S3jJpFm8FXFaTjQlRjl7TMiX+hRNXEZag9tr/hNdqmp0YfDeUJilreC0C++DHXDbwguqLS1qdv3sbIHBcfB8X9DbbuFp3eTBZYHbsXhvsumBxvCuIv2Drqf692LBzzdeHTd0xsJSN0ekV5UePKyas6Z0AH3wXVIJinK4e3EZ86V+Y2WKpshyRUaQ3pSMbr6DlpgpTSnGhs1NKLQKdAW/luSusJRm99+ofhT8BvC6WBET/Au1jlUWUKgRPI8cs/Fv3tLHN7Wl+iT+0rQpJZTNiEz3P9WwzRQqjHASg2REs=
