language: java
sudo: required
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "5033" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/lab234.jar -t 5033/se234-lab10-backend
  .
- docker push 5033/se234-lab10-backend
- docker pull 5033/se234-lab10-client
script:
- docker-compose -H "tcp://http://34.212.30.86:2561" up -d
cashe:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: lrm3en8nXvazdJM5OyA22xPNJQRAuBNYNwQzSJtVGKSQ2SLz9jVIwhFAw7vzxwrbqvBInSwzj76CKrrSKksiymJfS3UkLF3EdU5qbOJr/hp8vRdu1cR804NZ8Zn+Uv4AJ9z6MaNpxa52Vh6onfI18yuY4s4PGhlsbnIg/i2gC04Q+nnCUmk67IWvM7nwZoCmiQqOt+YrNMcHoP8XrEqyrYAYzpnXeZLIrVco0jl1cfNmij1A6CqDtrUjoIJkp4bl6dL9iWJY3tjUb83H4qHzz/22ayGTTI2YnmiFUB05zR0UIIqw4Sra4QFqEDPA6gXXZO55hRStcPKZTfitTPly9F2GWC976WX+BaLUNp4UJhsDvD1Ff8J0Waqul/VKNwzizwvKrC0sTmsLEOToyffkWSWqtL6++IKxU9c4owhc7fqJuCV0LGMjnPD3zhyufIrJ2K+w6lW4CY4ucC4AKAzUrB9VsyLR+Mgyn5ywaepsHxg/eVfCrga/3iJnvjl9kODCI0OBC+tWnpTdfhaNsjIhpmOmwlr/Pk+rfvInQPMEUX+rxTo1LusOOAnM/EdhJUhxMxR9JZTKBb8dwnwTD8IQg4kYbPmM1gOgRFu48USra4OMYv3W9429/oQgz0gu4ACHqGUlmUwmK7nwVeK5T7dsMFQMe7mtLHAaT+Smw92YYIw=
  - secure: aBRA3wqX93TYWmtL4BpJP8kf9oAOFcMMmmmRfNR+qnSzCVzBCwh+We9Jl153UssoeNdCXnVk5EhvqXCUUc/lSpKdInYsRvNFVhs98rNrDgvord1wXgC5Zmj8amMfdtvaoeowY2mHpvF7bJsPFciVofiEIrcsfsmunSadxzkSVdaV+PcV6Y3qq9C2JFWlGe8O/Jr92ykm9HJ5K70wLAGgKeqiz/ybR3p3EV73NbChyOzjcJZY3umNY26DGiZVj6gKu620ZwK8jYZN+9zeJAXs023BWvs/KIe9nRJe198S/NchQ2mx+IyYVV3jUQgZqLfUIsUNnZiwKgyW+zj9pGtxfcuE9U9clpkx55aHgElZVbYqeY+DyGIDlOEtelpAv1sj3vuARF7XajLJ/04txAzAcW8b5S1sl0IEPknGvaQX7vQIaS7mJFxXTDWbYt2imO5i/48bur7DIy6ldOOgVWzeAPDNdjDzduiYncr8ImIClvlEcQ9rCINPMlgyOmUGH7exbNZEv/tSLMwM+kLuGLu8sghKSyrAhbEK5bHdnhGWJoocpd8glg7VBm5sR81wpcVNRxIRM7h+ntyCR9IRMtOfHUGvrYMR5kPOwEColX4vmpFvynsC6twdMSDJCkW/q2P8NFOPviMeeJmLCci7jOY3v4q7sOLnj5DRM8ONpY1VaOU=
  - secure: SIaSa/PcE0dR7w1uN/gPIz5m3Q/hk1vSFFNHQP1H++WMVV+hQ4KbbFciN5/GvVvW2y1CyIOGYMDKVfUYKDwWsyzrEjTnNKglMSpWqyApEth9xJjM3fB6kTQREkfi/z6HOMVml+aw1SMQcJGit1jAwI/MTeTndJlAiS7lDgMJ4UZ8X4oyphMyt54gbnujnjgxPnRveQNxo2CCBY8BAVwQq0FqLXsxQd5LTVYDfaxq1OTt23dxR7vICLpxHoAsOj3epbXPLHAvFt2m2OT8yNuxvQDTQ31jpGIQ3U2Fi7dscCqXdykLAcEoKc+KzrHJ0jxH4GytWS1Ztr5OuYX05mBAgi7gvm5X7gz5HzfTat3bNz0UZLWIUoqvUA6xmU30UNJ0qcF8KxOyFdQoaZ4UuKe5CHFq9sA5f6v+hcIHR8K+uKPdc/AKYkmuSvA5rwZfkxx+ivczAJoiJ4KeGdBERvJrN6HgeSz+p7Q6YCaVZzU3gbUu7Z106YCby379d29BafvwPc2ZuxxOsNgwsAUDafJ6Qo0epoXG4oq/GIDPpl4vZOD6AAFZCSVI+oSta0i5jUT0Sveb5ff9BRvMvMV9W5OkIthifwoIiozjTWtG6+6EvlTIWwsiaJu1XWOx1CP1zMfFxVbjtf1bOH5cO3azRzn/0uyuoIagLwl3WQv2bChpQgE=
